# Source: https://docs.github.com/en/actions/publishing-packages/publishing-java-packages-with-gradle#:~:text=With%20this%20configuration%2C%20you%20can%20create%20a%20workflow%20that%20publishes%20your%20package%20to%20GitHub%20Packages%20by%20running%20the%20gradle%20publish%20command

name: Java Kernel - Release Workflow
on:
  push:
    branches:
      - 'main'
#  release:
#    types: [published]
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Publish package
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}