# Source: https://docs.github.com/en/actions/publishing-packages/publishing-java-packages-with-gradle#:~:text=With%20this%20configuration%2C%20you%20can%20create%20a%20workflow%20that%20publishes%20your%20package%20to%20GitHub%20Packages%20by%20running%20the%20gradle%20publish%20command

name: Java Kernel - SNAPSHOT - Workflow
on:
  push:
    branches:
      - 'main'
jobs:
  publish:
    runs-on: ubuntu-latest
    environment: io-bensing-maven-snapshots
    env:
      KOSLI_API_TOKEN: ${{ secrets.KOSLI_API_TOKEN }}
      KOSLI_OWNER: ${{ secrets.KOSLI_OWNER}}
    steps:

      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup Kosli CLI
        uses: kosli-dev/setup-cli-action@v1

      - name: Kosli - Declare a pipeline
        run: kosli pipeline declare --pipeline bensing-ledger -t pull-request,artifact,test

#      - name: Check a Pull Request exists for this commit
#        run: kosli assert github-pullrequest

      - name: Authenticate to Google Cloud Console
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_ARTIFACTORY_SERVICE_ACCOUNT}}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Install & Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '16'
          distribution: 'adopt'
          cache: 'gradle'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b

      - name: Build & test
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: test

      - name: Collect test artifacts - [./build/test-results] directory
        run: |
          kosli pipeline artifact report creation ./build/test-results \
            --artifact-type dir \
            --description 'The gradle build/test-results directory' \
            --owner Bensing-IO \
            --pipeline bensing-ledger

      - name: Publish package to artifact repository
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: publish

      - name: Kosli - Report Creation of JAR Artifact
        run: |
          for jar_path in ./build/libs/*.jar; do
            jar_fileName="${jar_path##*/}"   
            kosli pipeline artifact report creation $jar_path \
              --artifact-type file \
              --description $jar_fileName \
              --owner Bensing-IO \
              --pipeline bensing-ledger
          done

      - name: Kosli - Log Expected Deployment
        run: |
          for jar_path in ./build/libs/*.jar; do
            jar_fileName="${jar_path##*/}"             
            kosli expect deployment $jar_path \
              --artifact-type file \
              --description $jar_fileName \
              --environment io-bensing-maven-snapshots \
              --owner Bensing-IO \
              --pipeline bensing-ledger
          done

      - name: Kosli - Add Jar to Environment Allow List
        run: |
          for jar_path in ./build/libs/*.jar; do
            jar_fileName="${jar_path##*/}"             
            kosli environment allowedartifacts add $jar_path \
              --artifact-type file \
              --environment io-bensing-maven-snapshots \
              --owner Bensing-IO \
          done

      - name: Kosli - Report Deployment Approved
        run: |
          for jar_path in ./build/libs/*.jar; do
            jar_fileName="${jar_path##*/}"                       
            kosli pipeline approval report $jar_path \
              --artifact-type file \
              --description $jar_fileName \
              --newest-commit $(git rev-parse HEAD) \
              --oldest-commit $(git rev-parse HEAD~1) \
              --owner Bensing-IO \
              --pipeline bensing-ledger 
          done